// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfH4eUrJNYWixHLmZ4NSzSMamgG3vnT1Y',
    appId: '1:268248668862:web:7f0344c1ee7f0fdb835cef',
    messagingSenderId: '268248668862',
    projectId: 'aifit-a7f6b',
    authDomain: 'aifit-a7f6b.firebaseapp.com',
    databaseURL: 'https://aifit-a7f6b-default-rtdb.firebaseio.com',
    storageBucket: 'aifit-a7f6b.firebasestorage.app',
    measurementId: 'G-1QC4CQBTFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLjB0VTpiDKcSEQMbKPIYAolIRkyrsIqk',
    appId: '1:268248668862:android:4fb9ca0c4627a45a835cef',
    messagingSenderId: '268248668862',
    projectId: 'aifit-a7f6b',
    databaseURL: 'https://aifit-a7f6b-default-rtdb.firebaseio.com',
    storageBucket: 'aifit-a7f6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq6SXj_CyT3hAqiZzAhgEYzQS4Bqlbufc',
    appId: '1:268248668862:ios:f0db0f429ce41a2e835cef',
    messagingSenderId: '268248668862',
    projectId: 'aifit-a7f6b',
    databaseURL: 'https://aifit-a7f6b-default-rtdb.firebaseio.com',
    storageBucket: 'aifit-a7f6b.firebasestorage.app',
    iosClientId: '268248668862-7eghtc9pte6vk8r92197amh361692ipt.apps.googleusercontent.com',
    iosBundleId: 'com.example.aifit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq6SXj_CyT3hAqiZzAhgEYzQS4Bqlbufc',
    appId: '1:268248668862:ios:f0db0f429ce41a2e835cef',
    messagingSenderId: '268248668862',
    projectId: 'aifit-a7f6b',
    databaseURL: 'https://aifit-a7f6b-default-rtdb.firebaseio.com',
    storageBucket: 'aifit-a7f6b.firebasestorage.app',
    iosClientId: '268248668862-7eghtc9pte6vk8r92197amh361692ipt.apps.googleusercontent.com',
    iosBundleId: 'com.example.aifit',
  );

}